# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CffCli < Formula
  desc "CLI tool to view the timetables of the Swiss federal railways (SBB CFF FFS)."
  homepage "https://github.com/aurel-bul/cff-cli"
  version "2.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aurel-bul/cff-cli/releases/download/v2.3.0/cff-cli_Darwin_x86_64.tar.gz"
      sha256 "3dcc3138cb902a41b4d73b0fc8b69a65dbade9fb7d9b18c377b36ee5f93eec19"

      def install
        bin.install "cff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aurel-bul/cff-cli/releases/download/v2.3.0/cff-cli_Darwin_arm64.tar.gz"
      sha256 "109d9c1050f85ef37f1062fc5cfd0df344cc12f2ee015d0385c544496dbe2418"

      def install
        bin.install "cff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aurel-bul/cff-cli/releases/download/v2.3.0/cff-cli_Linux_x86_64.tar.gz"
      sha256 "06dee414b5f33cabbb37b2d02773e3310376639224f0d172e0f51813bdecdf32"
      def install
        bin.install "cff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aurel-bul/cff-cli/releases/download/v2.3.0/cff-cli_Linux_arm64.tar.gz"
      sha256 "9a21c5650f2139ad8090815c436f10e77d744cf6ef8e7940f533464f87e54e00"
      def install
        bin.install "cff"
      end
    end
  end
end
